### PR TITLE
feat: aes + pem + rsa

### PR DESCRIPTION
**Pull request by realvarx**
**- What I did**
Implemented automatic `pkamPrivateKey` AES decryption and atKeys "from:atSign" challenge signing (pkam).

**- How I did it**

- AES functionality:
    - Compiled a custom firmware ([this](https://github.com/atsign-foundation/at_pico_w/blob/feature/aes-pem-rsa/custom_firmware.uf2) file) for the Pico W, [activating the AES CTR mode support](https://github.com/micropython/micropython/issues/9614), as it isn't enabled by default in official builds.
    - `aes.py` file contains the methods used for AES descryption

- ASN.1 functionality (pem key) :
    - Used [this](https://github.com/mkomon/uasn1) library and made some minor modifications to it, so it can decode an octet string properly. This is necessary because the atKeys file contains a PKCS8 key (the `pkamPrivateKey`), from which we extract its RSA Private Key (PKCS1 key) DER structure (which is, the `n e d p q` parameters that we need for our `privateKey`).
    - `pem_service.py` file contains the methods used to process the pkamPrivateKey and obtain the DER parameters.
 
- RSA functionality (challenge signing - pkam) :
    - Used [this](https://github.com/GoogleCloudPlatform/iot-core-micropython) library to recover the RSA Private Key from the DER structure parameters and sign the challenge provided by the DESS after a "from:atSign" verb was sent.

**- How to verify it**
Follow the new steps in the [README.md](https://github.com/atsign-foundation/at_pico_w/tree/feature/aes-pem-rsa#usage) file from this branch.

**- Description for the changelog**
Automatic `pkamPrivateKey` AES decryption and pkam challenge signing implemented

### CODE REVIEW

**Review by cpswan — APPROVED** [review]

**Comment by cpswan** [comment]
Thanks @realvarx mostly LGTM, so I've approved and merged.

The one thing I'd like to change is the way we handle the custom firmware. The Allstar app will be along in the next day or so to raise an issue about having binary files in the repo. What I'd rather do here is:

1. Have the source for the firmware here, so people can see what's going on, and build/tweak it themselves if they'd like to.
2. Build the firmware from that source using a GitHub Action, and make it available in releases (we can do this manually at first).

**Comment by realvarx** [comment]
> Thanks @realvarx mostly LGTM, so I've approved and merged.
> 
> The one thing I'd like to change is the way we handle the custom firmware. The Allstar app will be along in the next day or so to raise an issue about having binary files in the repo. What I'd rather do here is:
> 
> 1. Have the source for the firmware here, so people can see what's going on, and build/tweak it themselves if they'd like to.
> 2. Build the firmware from that source using a GitHub Action, and make it available in releases (we can do this manually at first).

The source is the MicroPython repo itself, [with a few lines of code added in some files](https://github.com/micropython/micropython/issues/9614) (the ones required to enable AES CTR mode). Then it's necessary to install a concrete gcc compiler (if I'm not wrong, depending of your system arm/x86) to compile the firmware manually, and convert it to .uf2 format (there is a tool included in the MicroPython repo for that). 

I don't know if GitHub Actions can do that for us, I honestly don't have any knowledge about GH Actions

**Comment by cpswan** [comment]
In which case @realvarx what I'm going to do is:

1. Create a fork of micropython in atsign-foundation
2. Create a branch from master that has the AES CTR mods in place
3. Manually build a firmware.uf2 and place it in releases
4. Remove the binary from this repo and update the README to point to the releases in our fork
5. See if we can automate future build/release so as we merge upstream updates we can keep things up to date.

CC @cconstab @JeremyTubongbanua @TylerTrott as you'll probably want to keep track of this.

**Comment by TylerTrott** [comment]
> In which case @realvarx what I'm going to do is:
> 
> 1. Create a fork of micropython in atsign-foundation
> 2. Create a branch from master that has the AES CTR mods in place
> 3. Manually build a firmware.uf2 and place it in releases
> 4. Remove the binary from this repo and update the README to point to the releases in our fork
> 5. See if we can automate future build/release so as we merge upstream updates we can keep things up to date.
> 
> CC @cconstab @JeremyTubongbanua @TylerTrott as you'll probably want to keep track of this.

Is this information + the docs within the ReadMe something we should add to our docs site? @cpswan

**Comment by realvarx** [comment]
> In which case @realvarx what I'm going to do is:
> 
> 1. Create a fork of micropython in atsign-foundation
> 2. Create a branch from master that has the AES CTR mods in place
> 3. Manually build a firmware.uf2 and place it in releases
> 4. Remove the binary from this repo and update the README to point to the releases in our fork
> 5. See if we can automate future build/release so as we merge upstream updates we can keep things up to date.
> 
> CC @cconstab @JeremyTubongbanua @TylerTrott as you'll probably want to keep track of this.

That's a good idea, I'll test it out in my Pico W when it's ready

**Pull request merged**
